// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SKE_Core","status":true,"description":"Base plugin for the SKE library.","parameters":{}},
{"name":"SKE_Titlescreen","status":true,"description":"Engine for creating titlescreen layout","parameters":{}}
];
